[build]
  # Pas de build process nécessaire pour une app statique
  publish = "."
  
[functions]
  # Configuration des fonctions
  directory = "netlify/functions"
  # Force le runtime Node.js
  node_bundler = "esbuild"
  
[build.environment]
  # Variables d'environnement pour le build (si nécessaire)
  NODE_VERSION = "18"

# Redirections pour SPA
[[redirects]]
  # Redirection pour auth-callback.html
  from = "/auth-callback"
  to = "/auth-callback.html"
  status = 200

[[redirects]]
  # Redirection pour analytics.html
  from = "/analytics"
  to = "/analytics.html"
  status = 200

[[redirects]]
  # Redirection pour les routes de l'application
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Variables d'environnement à définir dans l'interface Netlify :
# SUPABASE_URL=https://votre-projet.supabase.co
# SUPABASE_ANON_KEY=votre-cle-anonyme
# SUPABASE_SERVICE_ROLE_KEY=votre-cle-service
# JWT_SECRET=votre-secret-jwt-super-secure
